language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

jobs:
  fast_finish: true
  include:
    - php: 5.4
      dist: precise
    - php: 5.5
      dist: trusty

script:
  - cd tests && phpunit --coverage-text .
